version: "3.9"
services:
  mongodb:
    container_name: daoanhthanh_mongodb
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - daoanhthanh

  # postgres:
  #   container_name: postgresql
  #   restart: always
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_PASSWORD=example
  #   networks:
  #     - sunoil
  #
  # redis:
  #   container_name: redis
  #   restart: always
  #   image: redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - sunoil
  # #
  mysql:
    container_name: MySQL
    restart: always
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - daoanhthanh

networks:
  daoanhthanh:
    driver: bridge
